version: "3.9"

services:
  db:
    image: docker.io/postgres:18
    container_name: pg-main
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10

  redmine:
    image: docker.io/redmine:6.1.0
    container_name: redmine
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    environment:
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_DATABASE: ${REDMINE_DB}
      REDMINE_DB_USERNAME: ${REDMINE_DB_USER}
      REDMINE_DB_PASSWORD: ${REDMINE_DB_PASS}
    ports:
      - "${REDMINE_PORT:-3000}:3000"
    volumes:
      - redmine_files:/usr/src/redmine/files
      - redmine_plugins:/usr/src/redmine/plugins
      - redmine_themes:/usr/src/redmine/public/themes

  mattermost:
    image: docker.io/mattermost/mattermost-team-edition:11.0
    container_name: mattermost
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    environment:
      MM_SQLSETTINGS_DRIVERNAME: "postgres"
      MM_SQLSETTINGS_DATASOURCE: "postgres://${MM_DB_USER}:${MM_DB_PASS}@db:5432/${MM_DB}?sslmode=disable&connect_timeout=10"
      MM_SERVICESETTINGS_SITEURL: "${MM_SITEURL}"
      # Useful defaults:
      MM_LOGSETTINGS_ENABLECONSOLE: "true"
      MM_PLUGINSETTINGS_ENABLE: "true"
    ports:
      - "${MATTERMOST_PORT:-8065}:8065"
    volumes:
      - mm_config:/mattermost/config
      - mm_data:/mattermost/data
      - mm_logs:/mattermost/logs
      - mm_plugins:/mattermost/plugins
      - mm_client_plugins:/mattermost/client/plugins
      - mm_bleve_indexes:/mattermost/bleve-indexes

volumes:
  pg_data:
  redmine_files:
  redmine_plugins:
  redmine_themes:
  mm_config:
  mm_data:
  mm_logs:
  mm_plugins:
  mm_client_plugins:
  mm_bleve_indexes:
